### PR TITLE
Homework hopefully ready for deployment :)

### PR DESCRIPTION
**Pull request by hyperkarmic**
Hi Suraj!!!  Hopefully this is the vast majority of the homework task done :)

### CODE REVIEW

**Comment by CJLynagh1992** [comment]
`<div class="header">
    <h1>Hori<span class="seo">seo</span>n</h1>
    <div>
      <ul>
        <li>
          <a href="#search-engine-optimization">Search Engine Optimization</a>
        </li>
        <li>
          <a href="#online-reputation-management">Online Reputation Management</a>
        </li>
        <li>
          <a href="#social-media-marketing">Social Media Marketing</a>
        </li>
      </ul>
    </div>`

Hi Simon - I would recommend having a think about semantic HTML elements and where they could be used above to make the content easier to understand. As a hint - there are 2 parts here where would suggest using semantic elements... drop me a line if you want to discuss these :D

**Comment by colum-j-lynagh** [comment]
` <div class="hero"></div> `

Looks great so far Simon. As Im reviewing I will add some suggestions here in the comments. 

For example: I would recommend looking at adding a title attribute above to optimise the website. This image may be something which the company feel represents their brand strongly and a title attribute describing the image would improve the sites overall accessibility :D

**Comment by colum-j-lynagh** [comment]
I love the rationalisation of the sections within the main. You're also spot on in using the id attribute although I would suggest using this on the main as opposed to in each section. The id is typically used to identify a single element whereas class is used on many.

**Comment by colum-j-lynagh** [comment]
Your 'alts' look great throughout the sections also. 

Theres a small typo on line 66

**Comment by CJLynagh1992** [comment]
Similarly to my content above on ids and classes. I would recommend changing `<aside class="benefits">` to an id for the same reasons

**Comment by colum-j-lynagh** [comment]
Have a look at your aside element and think about the content within. This is another case where is would be useful to use a more descriptive element than the div :D

**Comment by colum-j-lynagh** [comment]
`</footer>`

`</html>` 

Theres a missing closing tag here. You'll spot it and kick yourself

**Pull request merged**
